- name: Create directory for virtual environments
  file: path={{ pyenv_dir }} state=directory

- name: Create mainsite virtualenv
  command: /usr/bin/virtualenv -p /usr/bin/python2.7 {{ pyenv_dir }}/mainsite

- name: Install git
  sudo_user: root
  apt: package=git state=present

- name: Create directory for checking out apps
  file: path={{ app_dir }} state=directory

- name: Install dependencies to mainsite virtualenv
  pip: name={{ item['name'] }}
       version={{ item['version'] }}
       executable=pip
       virtualenv={{ pyenv_dir}}/mainsite 
       state=present
       extra_args="--download-cache {{ pip_cache }}"
  with_items:
#  - name: pelican 
#    version: 3.3
  - name: mynt 
    version: 0.2.3
#  - name: pipages 
#    version: ???

#  Tarball install since could not locate pipages version on pypi

- name: Install pipages
  pip: name=https://github.com/anandology/pipages/tarball/master
       executable=pip 
       virtualenv={{ pyenv_dir}}/mainsite 
       state=present

- name: Generate site
  shell: . {{ pyenv_dir }}/mainsite/bin/activate && pipages {{ hostname }} --repo git://github.com/pythonindia/python.org.in.git --engine mynt --root {{ mainsite_static_cache }}

- name: Delete site directory if it exists 
  sudo_user: root
  file: path={{ mainsite_static_root }} state=absent

- name: Create site directory
  sudo_user: root
  file: path={{ mainsite_static_root }} state=directory owner=www-data group=www-data mode=775

- name: Copy generated site content
  shell: cp -r {{ mainsite_static_cache }}/build/{{ hostname }}/* {{ mainsite_static_root }}
