- name: restart ssh
  service: name=ssh state=restarted

- name: restart iptables-persistent
  service: name=iptables-persistent state=restarted

- name: restart nginx
  service: name=nginx state=restarted

